name: drlnd_p2
channels:
    - pytorch
dependencies:
    - python=3.6.5
    - nose=1.3.7
    - numpy=1.14.5
    - matplotlib=3.0.2
    - pytorch=0.4.0
    - protobuf=3.5.2
    - toolz=0.9.0
    - multipledispatch=0.6.0
    - infinity=1.4
    - six=1.11.0
    - pip:
        - git+https://github.com/openai/gym.git@v0.9.6
        - git+https://github.com/Unity-Technologies/ml-agents.git@0.5.0a#egg=mlagents&subdirectory=ml-agents
        